# BUSCAR CLIENTES QUE TIENE MÁS DE UN CRÉDITO TOMADO
SELECT ID, POSTULANTES, POSTULANTES_NOMBRES FROM fid_creditos WHERE POSTULANTES IN 
(SELECT POSTULANTES FROM fid_creditos WHERE `ID_CADUCADO` =0 GROUP BY POSTULANTES HAVING COUNT(ID)>1 ) ORDER BY POSTULANTES ASC

