CREATE TABLE IF NOT EXISTS `fid_operatoria_cambiotasas` (
  `ID_OPERATORIA` int(11) NOT NULL,
  `FECHA` int(11) NOT NULL,
  `COMPENSATORIO` double NOT NULL,
  `SUBSIDIO` double NOT NULL,
  `MORATORIO` double NOT NULL,
  `PUNITORIO` double NOT NULL,
  PRIMARY KEY (`ID_OPERATORIA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




ALTER TABLE `fid_creditos` ADD `IVA` FLOAT NOT NULL AFTER `T_GASTOS_MIN` ;
UPDATE `fid_creditos` c JOIN `fid_operatorias` o ON c.ID_OPERATORIA = o.ID SET c.IVA=o.IVA;