/****** Object:  Table [dbo].[A_CREDITOS_CONTABLE]    Script Date: 01/05/2017 09:09:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[A_CREDITOS_CONTABLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NUM_CREDITO] [bigint] NOT NULL,
	[ID_FIDEICOMISO] [int] NOT NULL,
	[ID_OPERATORIA] [int] NOT NULL,
	[ID_CLIENTE_CREDITOS] [int] NOT NULL,
	[ID_CLIENTE_HO] [int] NOT NULL,
	[CUOTA] [int] NOT NULL,
	[FECHA_AAAA_PERIODO] [int] NOT NULL,
	[FECHA_MM_PERIODO] [int] NOT NULL,
	[FECHA_DD_PERIODO] [int] NOT NULL,
	[PROCESO_R_C] [char](1) NOT NULL,
	[ESTADO_PROCESO] [int] NOT NULL,
	[CAPITAL] [money] NOT NULL,
	[INT_COMP] [money] NOT NULL,
	[IVA_COMP] [money] NOT NULL,
	[INT_AC] [money] NOT NULL,
	[IVA_AC] [money] NOT NULL,
	[GASTOS] [money] NOT NULL,
	[INT_MOR] [money] NOT NULL,
	[IVA_MOR] [money] NOT NULL,
	[INT_PUN] [money] NOT NULL,
	[IVA_PUN] [money] NOT NULL,
	[FECHA_PROCESO] [smalldatetime] NULL,
	[FECHA_FACTURADO] [smalldatetime] NULL,
	[FAC_EMP] [int] NOT NULL,
	[FAC_TIP] [char](1) NOT NULL,
	[FAC_TCO] [char](2) NOT NULL,
	[FAC_SUC] [int] NOT NULL,
	[FAC_NCO] [bigint] NOT NULL,
	[FECHA_RECIBO] [smalldatetime] NULL,
	[REC_EMP] [int] NOT NULL,
	[REC_TIP] [char](1) NOT NULL,
	[REC_TCO] [char](2) NOT NULL,
	[REC_SUC] [int] NOT NULL,
	[REC_NCO] [bigint] NOT NULL,
	[ASIENTO_FAC] [bigint] NOT NULL,
	[ASIENTO_REC] [bigint] NOT NULL,
	[FECHA_AUT_CAE] [smalldatetime] NULL,
	[ESTADO_CAE] [bigint] NOT NULL,
	[FECHA_ENV_CORREO] [smalldatetime] NULL,
	[ESTADO_CORREO] [int] NOT NULL,
	[OBSERV1] [varchar](100) NOT NULL,
	[OBSERV2] [varchar](100) NOT NULL,
        [ID_EVENTO] INT DEFAULT 0,
        [OPERATORIA] [varchar](64) NOT NULL,
 CONSTRAINT [PK_A_CREDITOS_CONTABLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_NUM_CREDITO]  DEFAULT ((0)) FOR [NUM_CREDITO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_ID_FIDEICOMISO]  DEFAULT ((0)) FOR [ID_FIDEICOMISO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_ID_OPERATORIA]  DEFAULT ((0)) FOR [ID_OPERATORIA]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_ID_CLIENTE_CREDITOS]  DEFAULT ((0)) FOR [ID_CLIENTE_CREDITOS]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_ID_CLIENTE_HO]  DEFAULT ((0)) FOR [ID_CLIENTE_HO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_CUOTA]  DEFAULT ((0)) FOR [CUOTA]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_Table_1_FECHA]  DEFAULT ((0)) FOR [FECHA_AAAA_PERIODO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_FECHA_MM_PERIODO]  DEFAULT ((0)) FOR [FECHA_MM_PERIODO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_FECHA_DD_PERIODO]  DEFAULT ((0)) FOR [FECHA_DD_PERIODO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_CAPITAL]  DEFAULT ((0)) FOR [CAPITAL]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_INT_COMP]  DEFAULT ((0)) FOR [INT_COMP]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_IVA_COMP]  DEFAULT ((0)) FOR [IVA_COMP]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_GASTOS]  DEFAULT ((0)) FOR [GASTOS]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_INT_MOR]  DEFAULT ((0)) FOR [INT_MOR]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_IVA_MOR]  DEFAULT ((0)) FOR [IVA_MOR]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_INT_PUN]  DEFAULT ((0)) FOR [INT_PUN]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_IVA_PUN]  DEFAULT ((0)) FOR [IVA_PUN]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_FAC_EMP]  DEFAULT ((0)) FOR [FAC_EMP]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_FAC_TIP]  DEFAULT ('') FOR [FAC_TIP]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_FAC_TCO]  DEFAULT ('') FOR [FAC_TCO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_FAC_SUC]  DEFAULT ((0)) FOR [FAC_SUC]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_FAC_NCO]  DEFAULT ((0)) FOR [FAC_NCO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_REC_EMP]  DEFAULT ((0)) FOR [REC_EMP]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_REC_TIP]  DEFAULT ('') FOR [REC_TIP]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_REC_TCO]  DEFAULT ('') FOR [REC_TCO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_REC_SUC]  DEFAULT ((0)) FOR [REC_SUC]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_REC_NCO]  DEFAULT ((0)) FOR [REC_NCO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_ASIENTO_FAC]  DEFAULT ((0)) FOR [ASIENTO_FAC]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_ASIENTO_REC]  DEFAULT ((0)) FOR [ASIENTO_REC]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_ESTADO_CAE]  DEFAULT ((0)) FOR [ESTADO_CAE]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_ESTADO_CORREO]  DEFAULT ((0)) FOR [ESTADO_CORREO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_OBSERV1]  DEFAULT ('') FOR [OBSERV1]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_OBSERV2]  DEFAULT ('') FOR [OBSERV2]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_PROCESO_R_C]  DEFAULT ('R') FOR [PROCESO_R_C]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_ESTADO_PROCESO]  DEFAULT ((0)) FOR [ESTADO_PROCESO]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_INT_AC]  DEFAULT ((0)) FOR [INT_AC]
GO

ALTER TABLE [dbo].[A_CREDITOS_CONTABLE] ADD  CONSTRAINT [DF_A_CREDITOS_CONTABLE_IVA_AC]  DEFAULT ((0)) FOR [IVA_AC]
GO


CREATE TABLE [dbo].[A_CREDITOS_PROCESOS](
	[CREDITO] [tinyint] NULL,
	[CONTABILIDAD] [tinyint] NULL
) ON [PRIMARY]

GO

insert into A_CREDITOS_PROCESOS values (0,0)
GO


/*
incidencia 148094
Paso de creditos a contabilidad
Aqui se deben guardar los medios de cobro de los recuperos para los recibos en contabilidad
los medios posibles son:

DROP TABLE [dbo].[A_CREDITO_CONTABLE_COBROS]
*/

/****** Object:  Table [dbo].[A_CREDITO_CONTABLE_COBROS]    Script Date: 01/05/2017 11:16:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[A_CREDITO_CONTABLE_COBROS](
	[ID_CONTABLE] [bigint] NOT NULL,
	[ID_CREDITO] [bigint] NOT NULL,
	[MEDIO_COBRO] [CHAR](1) NOT NULL,
	[IMPORTE] [MONEY] NOT NULL,
	[FECHA] [smalldatetime] NULL,
	[ID_BANCO] [int] NOT NULL,
	[ID_CTA] [int] NOT NULL,
	[NUMERO_COMP] [varchar](50) NOT NULL,
	[FECHA_EMI_COMP] [date] NULL,
	[FECHA_VEN_COMP] [date] NULL,
	[LIBRADOR] [varchar](50) NOT NULL,
	[OBSERVACION] [varchar](100) NOT NULL,
 CONSTRAINT [PK_A_CREDITO_CONTABLE_COBROS] PRIMARY KEY CLUSTERED 
(
	[ID_CONTABLE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_ID_CONTABLE]  DEFAULT ((0)) FOR [ID_CONTABLE]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_ID_CREDITO]  DEFAULT ((0)) FOR [ID_CREDITO]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_MEDIO_COBRO]  DEFAULT ('') FOR [MEDIO_COBRO]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_ID_BANCO]  DEFAULT ((0)) FOR [ID_BANCO]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_ID_CTA]  DEFAULT ((0)) FOR [ID_CTA]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_NUMERO_COMP]  DEFAULT ('') FOR [NUMERO_COMP]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_LIBRADOR]  DEFAULT ('') FOR [LIBRADOR]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_OBSERVACION]  DEFAULT ('') FOR [OBSERVACION]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_IMPORTE]  DEFAULT (0) FOR [IMPORTE]
GO
