CREATE TABLE [dbo].[A_CREDITOS_PROCESOS](
	[CREDITO] [tinyint] NULL,
	[CONTABILIDAD] [tinyint] NULL
) ON [PRIMARY]

GO

insert into A_CREDITOS_PROCESOS values (0,0)
GO

ALTER TABLE A_CREDITOS_CONTABLE ADD ID_EVENTO INT DEFAULT 0
GO