CREATE TABLE [dbo].[A_CREDITOS_PROCESOS](
	[CREDITO] [tinyint] NULL,
	[CONTABILIDAD] [tinyint] NULL
) ON [PRIMARY]

GO

insert into A_CREDITOS_PROCESOS values (0,0)
GO

ALTER TABLE A_CREDITOS_CONTABLE ADD ID_EVENTO INT DEFAULT 0
GO

/*
incidencia 148094
Paso de creditos a contabilidad
Aqui se deben guardar los medios de cobro de los recuperos para los recibos en contabilidad
los medios posibles son:

DROP TABLE [dbo].[A_CREDITO_CONTABLE_COBROS]
*/

/****** Object:  Table [dbo].[A_CREDITO_CONTABLE_COBROS]    Script Date: 01/05/2017 11:16:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[A_CREDITO_CONTABLE_COBROS](
	[ID_CONTABLE] [bigint] NOT NULL,
	[ID_CREDITO] [bigint] NOT NULL,
	[MEDIO_COBRO] [CHAR](1) NOT NULL,
	[IMPORTE] [MONEY] NOT NULL,
	[FECHA] [smalldatetime] NULL,
	[ID_BANCO] [int] NOT NULL,
	[ID_CTA] [int] NOT NULL,
	[NUMERO_COMP] [varchar](50) NOT NULL,
	[FECHA_EMI_COMP] [date] NULL,
	[FECHA_VEN_COMP] [date] NULL,
	[LIBRADOR] [varchar](50) NOT NULL,
	[OBSERVACION] [varchar](100) NOT NULL,
 CONSTRAINT [PK_A_CREDITO_CONTABLE_COBROS] PRIMARY KEY CLUSTERED 
(
	[ID_CONTABLE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_ID_CONTABLE]  DEFAULT ((0)) FOR [ID_CONTABLE]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_ID_CREDITO]  DEFAULT ((0)) FOR [ID_CREDITO]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_MEDIO_COBRO]  DEFAULT ('') FOR [MEDIO_COBRO]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_ID_BANCO]  DEFAULT ((0)) FOR [ID_BANCO]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_ID_CTA]  DEFAULT ((0)) FOR [ID_CTA]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_NUMERO_COMP]  DEFAULT ('') FOR [NUMERO_COMP]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_LIBRADOR]  DEFAULT ('') FOR [LIBRADOR]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_OBSERVACION]  DEFAULT ('') FOR [OBSERVACION]
GO

ALTER TABLE [dbo].[A_CREDITO_CONTABLE_COBROS] ADD  CONSTRAINT [DF_A_CREDITO_CONTABLE_COBROS_IMPORTE]  DEFAULT (0) FOR [IMPORTE]
GO
